#!/usr/bin/env perl
# -*- perl -*-

##############################################################
#
# Benchmark setup for Heat Transfer
#
# Usage: setup-heat-transfer-bmark <bmark> <srcdir> <destdir>
#
# Setup benchmark to run in <destdir>
#
##############################################################

use strict;
use warnings;
use File::Basename;
use Getopt::Long;

sub Usage();
sub ErrorExit($);

#
# Turn on warnings
#
$^W = 1;

my $compare = undef;
my $data = undef;
my $iter = undef;
my $group = undef;
my $linkto = undef;
my $feeder = ''; # Ununsed. For backwards compatability.

#
# Find the root of the benchmarks directory tree.
#
my $benchmark_root = `awb-resolver --config=benchmarkdir`;
chomp($benchmark_root);
ErrorExit("Can't find benchmark root") if ($benchmark_root eq '');

#
# Parse the command line switches
#
if (! GetOptions('compare=s' => \$compare,
                 'data=s' => \$data,
#                 'iter=s' => \$iter,
                 'group=s' => \$group,
                 'feeder=s' => \$feeder,
                 'linkto=s' => \$linkto,
                )) {
    Usage();
}

if ($#ARGV != 2) {
    Usage();
}

my $bmark = $ARGV[0];
my $srcdir = $ARGV[1];
my $dstdir = $ARGV[2];
my $basedir = `pwd`;

print "BMARK: $bmark\n";
print "SRC: $srcdir\n";
print "DST: $dstdir\n";
print "BASE: $basedir\n";

if (! defined($group)) {
    $group = $bmark;
}

chdir($dstdir) or ErrorExit("Failed to cd to $dstdir");

mkdir('leap_debug') or ErrorExit("Failed to make 'leap_debug' directory");

# Copy input data files
if (defined($data)) 
{
   print "data: $data\n";
   symlink("${srcdir}/${data}_input.dat", "input.dat") or die("Failed to link to $data");
   symlink("${srcdir}/${data}_output_iter128_golden.hex", "output_golden.hex") or die("Failed to link to $data");
   
   #if (defined($iter))
   #{
   #    print "output iter: $iter\n"
       #symlink("${srcdir}/${data}_output_iter${iter}_golden.hex", "output_golden.hex") or die("Failed to link to $data");
   #}
}

# Store compare rules to config
open(ENV, '>>config/env.sh') or die("Failed to open config/env.sh");
if (defined($compare)) {
    print ENV "compare=\"${compare}\"\n";
}
close(ENV);

system("cp -f ${srcdir}/run.bmark run");
chmod(0755, "run");

exit(0);

sub Usage() {
    print STDERR "Usage: setup-heat-transfer-bmark [--compare <compare commands>]\n";
    print STDERR "                                 [--data <input file>]\n";
#    print STDERR "                                 [--iter <golden output iteration>]\n";
    print STDERR "                                 [--group <name>]\n";
    print STDERR "                                 <bmark> <srcdir> <dstdir>\n";
    exit(1);
}

sub ErrorExit($) {
    print STDERR @_ . "\n";
    exit(1);
}
